# Spam or Ham (project 1)

## 1- Introduction with the Bernoulli model


We say that a random variables $X \in \{0, 1\}$ follows a Bernoulli distribution of parameter $\theta$ if $\mathbb{P}(X = 1) = \theta$ and $\mathbb{P}(X = 0) = 1 − \theta$.


1.  Show that we can write the probability distribution of $X$ in a compact form as : 
$$
\mathbb{P}(X = x) = \theta^{x} (1 − \theta)^{1−x}
$$

2. Suppose now that we have a set of n independent variables $x_1,...,x_n$. If we note $n_1 = \sum_{i=1}^n \mathbb{1}_{\{x_i=1\}}$ and $n_0 = n − n_1$, show that :
$$
\mathbb{P}(x_1,\ldots,x_n \mid \theta)=\theta^{n_1} (1−\theta)^{n_0}
$$

3. Show that the maximum likelihood estimator is $\hat{\theta}_{ML} = \frac{n_1}{n}$

4. A conjugate prior for the Bernoulli distribution is the Beta distribution. 
$$
Beta(\theta \mid a, b) \propto \theta^{a−1} (1 − \theta)^{b−1}
$$
The Beta distribution has the following properties for its expectation and mode (for more details you can look in one of the books like the Bishop):
$$
\mathbb{E}(\theta) = \frac{a}{a+b} \text{, mode}(\theta) = \frac{a-1}{a+b-2}
$$

Show that with a $Beta(a,b)$ prior the posterior distribution 
$\mathbb{P}(\theta \mid x_1,\ldots, x_n)$
is proportional to $\theta^{n_1+a-1} \cdot (1 − \theta)^{n_0+b-1}$ 

5. (Those two questions are optional, you can also simply use the result in the following)

  a. Show that the maximum a posteriori _mode_ estimate is in the form $\bar{\theta}_{MAP} = \frac{n_1+a-1}{n+a+b-2}$

  b. Show that the maximum a posteriori 
_mean_ estimate is in the form $\hat{\theta}_{MAP} = \mathbb{E}(\theta \mid x_1,\ldots, x_n) = 
\int_{\theta =0}^1 \mathbb{P}(\theta \mid x_1\ldots x_n) d\theta  = \frac{n_1+a}{n+a+b}$


### Solution 1
We have two cases:
   - if $x = 1$, then $\mathbb{P}(X = x) = \theta = \theta^{1} (1 − \theta)^{0}$
   - if $x = 0$, then $\mathbb{P}(X = x) = 1 − \theta = \theta^{0} (1 − \theta)^{1}$. 

Thus, the compact form holds for both cases.

### Solution 2
So we have $n_1$ as the count of variables equal to 1 and $n_0$ as the count of variables equal to 0. Since the variables are independent, we can multiply their probabilities to get the joint probabilitys:
$$\mathbb{P}(x_1, \dots, x_n \mid \theta) = \prod_{i=1}^{n} \mathbb{P}(X = x_i) = \prod_{i=1}^{n_1} \mathbb{P}(X = 1) \prod_{j=1}^{n_0} \mathbb{P}(X = 0)$$
Expanding both products gives:
$$\prod_{i=1}^{n_1} \mathbb{P}(X = 1) = \prod_{i=1}^{n_1} \theta = \theta^{n_1}$$
$$\prod_{j=1}^{n_0} \mathbb{P}(X = 0) = \prod_{j=1}^{n_0} (1 - \theta) = (1 - \theta)^{n_0}$$
Therefore, we have:
$$\mathbb{P}(x_1, \dots, x_n \mid \theta) = \theta^{n_1} (1 - \theta)^{n_0}$$

### Solution 3
To find the maximum likelihood estimator (MLE) $\hat{\theta}_{ML}$, we need to define the likelihood function based on the joint probability derived in Solution 2:
$$L(\theta) = \mathbb{P}(x_1, \dots, x_n \mid \theta) = \theta^{n_1} (1 - \theta)^{n_0}$$
Now we take the natural logarithm of the likelihood function to simplify the differentiation process:
$$\log L(\theta) = n_1 \log(\theta) + n_0 \log(1 - \theta)$$
Now, we differentiate the log-likelihood with respect to $\theta$ and set it to zero to find the maximum:
$$\frac{d}{d\theta} \log L(\theta) = \frac{n_1}{\theta} - \frac{n_0}{1 - \theta} = 0$$
Solving for $\theta$, we get by cross-multiplying:
$$n_1 (1 - \theta) = n_0 \theta$$
$$n_1 - n_1 \theta = n_0 \theta$$
$$n_1 = (n_0 + n_1) \theta$$
Thus, we find (noting that $n = n_0 + n_1$):
$$\hat{\theta}_{ML} = \frac{n_1}{n}$$

### Solution 4
Using Bayes' theorem, we derive the posterior distribution as follows:
$$
\mathbb{P}(\theta \mid x_1,\ldots, x_n) = \frac{\mathbb{P}(x_1,\ldots, x_n \mid \theta) \cdot \mathbb{P}(\theta)}{\mathbb{P}(x_1,\ldots, x_n)}$$
Therefore, we have:
$$\mathbb{P}(\theta \mid x_1,\ldots, x_n) \propto \mathbb{P}(x_1,\ldots, x_n \mid \theta) \cdot \mathbb{P}(\theta)$$
Now, we substitute the likelihood and prior distributions:
$$\mathbb{P}(\theta \mid x_1,\ldots, x_n) \propto \theta^{n_1} (1−\theta)^{n_0} \cdot \theta^{a−1} (1 − \theta)^{b−1}$$
Combining the exponents, we get:
$$\mathbb{P}(\theta \mid x_1,\ldots, x_n) \propto \theta^{n_1+a-1} \cdot (1 − \theta)^{n_0+b-1}$$

### Solution 5 (optional)
Using the results from Solution 4, we can see that the posterior distribution is a Beta distribution:
$$\mathbb{P}(\theta \mid x_1,\ldots, x_n) \sim \text{Beta}(n_1 + a, n_0 + b)$$
This means that the parameters are $a' = n_1 + a$ and $b' = n_0 + b$. We can now plug them into the mode formula:
$$\bar{\theta}_{MAP} = \frac{(n_1 + a) - 1}{(n_1 + a) + (n_0 + b) - 2} = \frac{n_1 + a - 1}{n + a + b - 2}$$

And we can plug them into the mean formula:
$$\hat{\theta}_{MAP} = \mathbb{E}(\theta \mid x_1,\ldots, x_n) = \frac{n_1 + a}{n + a + b}$$

## Spam classifier

The goal of this small project is to use a Naive bayes classifier to build a spam filter. To build our filter, we will use a dataset of 5,572 SMS messages put together by Tiago A. Almeida and José María Gómez Hidalgo. 
The dataset and the article describing the dataset are in the whiteboard directory together with this notebook. Of note, the SMS messages have already been processed for ease of use: all punctuation marks have been removed and the text has been transformed into lowercase. It is also common practice to remove any stop words such as `a`, `as`, `the` and to perform stemming (reduce words to their base form, such as stripping  the final `s*` in plural words, or the `*ing` from verbs (e.g., running becomes run)). For the sake of simplicity, we did not do that in this exercise.

We will use a bag of word model:
 - We construct a corpus of the possible words $\mathcal{D} = \{w_1, \ldots , w_d\}$.
 - Each document is described by a vector of binary values $(x^{(1)}, \ldots , x^{(d)})$ where $x^{(i)} = 1$ if $w_i$ occurs in the document and $0$ otherwise.

The classification task is to predict for an SMS message if it is a _spam_ or a _ham_ (e.g. non-spam).

Our data is thus $\mathbf{x} = (x^{(1)},\ldots, x^{(d)})$, $x^{(i)} \in \{0,1\}$ and $y \in \{s,h\}$
We hypothesise that the values $x^{(i)}$ are drawn according to a Bernoulli distribution whose parameter depends on the class:
$$
\mathbb{P}(x^{(i)} \mid y = s) = \theta_{i,s}^{x^{(i)}} \cdot (1-\theta_{i,s})^{1-x^{(i)}}
$$
and 
$$
\mathbb{P}(x^{(i)} \mid y = h) = \theta_{i,h}^{x^{(i)}} \cdot (1-\theta_{i,h})^{1-x^{(i)}}
$$
As we will use a naive Bayes classifier, the occurences of the different words are independent from each other.
\begin{align}
\mathbb{P}(\mathbf{x} \mid y = s) & = \prod_{i=1}^{d} \mathbb{P} (x^{(i)} \mid y = s)\\
  & =  \prod_{i=1}^{d} \theta_{i,s}^{x^{(i)}} \cdot (1-\theta_{i,s})^{1-x^{(i)}}
\end{align}


## Importing library and loading dataset

In [1]:
%matplotlib inline
import numpy as np
from collections import Counter

##Load the dataset (if in the same directory as the notebook)
sms_data = np.loadtxt("./SMSSpamCollection_cleaned.csv", delimiter="\t", skiprows=1, dtype=str)

## create test data set for checkpointing
checkpoint_data = np.array([['spam', 'dear researcher submit manuscript money'], 
          ['ham','dear friend meet beer'],
          ['ham', 'dear friend meet you']], dtype=str)

In [2]:
##Check the dataset
sms_data

array([['ham',
        'go until jurong point  crazy   available only in bugis n great world la e buffet    cine there got amore wat   '],
       ['ham', 'ok lar    joking wif u oni   '],
       ['spam',
        'free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005  text fa to 87121 to receive entry question std txt rate t c s apply 08452810075over18 s'],
       ...,
       ['ham',
        'pity    was in mood for that  so   any other suggestions '],
       ['ham',
        'the guy did some bitching but i acted like i d be interested in buying something else next week and he gave it to us for free'],
       ['ham', 'rofl  its true to its name']], dtype='<U910')

In [3]:
##Check the size of the dataset
num_messages = sms_data.shape[0]
print(num_messages)

##third message is a...
print("Third message is a:", sms_data[2][0])
##dividing the third message into words
print(sms_data[2][1].split())

5572
Third message is a: spam
['free', 'entry', 'in', '2', 'a', 'wkly', 'comp', 'to', 'win', 'fa', 'cup', 'final', 'tkts', '21st', 'may', '2005', 'text', 'fa', 'to', '87121', 'to', 'receive', 'entry', 'question', 'std', 'txt', 'rate', 't', 'c', 's', 'apply', '08452810075over18', 's']


## 2 - Construction of the Corpus

Construct the corpus $\mathcal{D}$ of all words in the dataset. The corpus will be represented as a hash table where each key is a unique word in the dataset and each value is the row index for that word. 
 - How many unique words are there? 
 - What are the 10 most common words (_e.g._ occuring in the most documents)?
 - Transform the set of messages in the form of a binary matrix of word occurrences.
 
 You can evaluate whether your implementation works using the checkpoint_data array. For this dataset the corpus could look as follows :

`{'dear': 0, 'researcher': 1, 'submit': 2, 'manuscript': 3, 'money': 4, 'friend': 5, 'meet': 6, 'beer': 7, 'you': 8}`
(of course you could have other index values for the words). 

The recoding of the checkpoint data will give you the following numpy array:

```
[[1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 1.]]
```

In [ ]:
def construct_corpus(data):
    """
    np.array[str, str] -> dict[str:int]
    
    from a 2D array of str, return a dict
    """
    ##Your code here

##test



In [ ]:

    
def recode_messages(data, corpus):
    """
    np.array[str, str] * dict[str:int] -> np.array[int, int]
    
    returns the binary matrix encoding 
    """
    ##Your code here


D = construct_corpus(sms_data)

sms_matrix = recode_messages(sms_data, D)



    

## 3 - Construct a training and a testing set and estimation of parameters


To do the evaluation of the model afterward we will split the dataset randomly in two: 
- one dataset for training (80% of the messages) 
- one dataset for testing (20% of the messages).

If you are familiar with it, you can use the `sklearn.model_selection` functions to construct the train and test datasets.


In [ ]:
def train_test_split(X, Y, train_percentage=0.8):
    assert X.shape[0] == Y.shape[0]

    number_examples = X.shape[0]
    num_train = int(train_percentage * number_examples)
    ##Your code here
    


## 4 - Estimation of the model parameters

We will now estimate our model on the training set. This means estimating two types of parameters: the class prior, and the conditional word occurrence probabilities.

1.  Estimate the class prior $\mathbb{P}(c) = \mathbb{P}(y = c), (c = s, h)$
2.  Using the results from section 1, compute the Maximum a posteriori estimator for the $d \times 2$ matrix of parameters (reminder $\theta_{i,j} = \mathbb{P}(x=i \mid y = j)$).
 $$
 \Theta = \left(
 \begin{array}{cc}
 \theta_{1,h}   & \theta_{1,s} \\
 \theta_{2,h} & \theta_{2,s} \\
 \vdots & \vdots \\
 \theta_{d,h} & \theta_{d,s} \\
 \end{array}
 \right).
 $$ You can use as conjugate prior a Beta(1, 1) distribution for instance (then $\theta_{i,c} = \frac{n_{i,c}+1}{N+2}$ where $n_{i,c}$ is the number of documents from the class $c$ where the word $w_i$ is present and $N$ is the total number of documents of that class).

 When applied to the checkpoint data, your $\Theta$ matrix should look like this:

 ```
 # h    s
 [[0.75 0.66666667]  #'dear'
  [0.25 0.66666667]  #'researcher'
  [0.25 0.66666667]  #'submit'
  [0.25 0.66666667]  #'manuscript'
  [0.25 0.66666667]  #'money'
  [0.75 0.33333333]  #'friend'
  [0.75 0.33333333]  #'meet'
  [0.5  0.33333333]  #'beer'
  [0.5  0.33333333]] #'you'
 ```

3. Represent the fitted word occurrence class conditional probabilities $(\theta_{i,h})_{i \in \mathcal{D}}$ and $(\theta_{i,s})_{i \in \mathcal{D}}$. You can represent it as two barplots, like shown in the lecture at the end of the "Naive Bayes for document" part. 


In [ ]:
## Your code here for class priors
    
def estimate_proportions(data_matrix):
    """
    estimate the matrix theta
    """
    #your code here
    
##
Dico = {'dear': 0, 'researcher':1, 'money': 2, 'friend': 3 }
#sentence 1 dear friend money 
#sentence 2 dear researcher friend
#sentence  friend money money
datam = np.array([[1, 0, 1, 1],[1, 1, 0, 1],[0, 0, 1, 1]], dtype = int)



## 4 - Message classification


4. Classify the messages in the test set using the Maximum a posteriori rule, and evaluate the performance of the model by computing the True Positive Rate (also called Sensitivity) and the False Positive Rate (the same as 1-Specificity). When performing the evaluation, keep in mind that the test set should not have access to the dictionary that was constructed during the training step. 

5. The performance of the model above was obtained by using a classification threshold of $0.5$ on the posterior probability. In other words, if $\mathbb{P}(y = s \mid \mathbb{x}) \ge 0.5$ then the message is classified as spam. Draw a ROC curve for your classifier. Note that you have to consider multiple values of the threshold to draw the ROC curve.

6. Why did we use the Maximum a posteriori estimator rather than the maximum likelihood one?




## 5 - Extension of the model 

One extension of the model is to consider a matrix of word counts instead of simply their presence/absence. 
The model will change in various ways in this case: 
   - We will count the total number of occurence in the spam or the ham set for each word.
   - the words are now considered to occur independently along the sentence (independent Multinoulli). Thus, for a document with k words $\mathbf{v}=(v_1,\ldots, v_k)$
    \begin{align}
    \mathbb{P}(\mathbf{v} \mid y = s) 
  & =  \prod_{t=1}^{k} p_{v_t}
    \end{align}
       where $p_v$ is the probability to observe a word $v$
       
Note that with this new model we compute a product over the positions in the sentence while the bernoulli model did a product over all the words in the corpus.

For the end of this project, you will implement the 

1. Rewrite the likelihood of a sentence such that it only needs on a vector of counts of each word $\mathbb{c} = (c^{(1)}, c^{(2)}, \ldots, c^{(d)})$. From this likelihood formulation provide ML estimators for the parameters $p_{i}^{h}$ and $p_i^{s}$ of the model. 
2. Implement the computation of the posterior class probabilities. This question can be interpreted in different ways, depending on the modeling choice. Please explain your choices. Feel free to use additional external resources (and cite them) to guide you in this task.
3. Compare its accuracy and ROC curve with the previous model on a test set (*e.g.* go over section 3 and 4 again for this model).

